### ISSUE TITLE
Unknown class TPKeyboardAvoidingScrollView in InterfaceBuilder

### ISSUE THREAD

**Issue by AnGe724** [fstehle/Xamarin-TPKeyboardAvoiding.iOS#1]
I've added the TPKeyboardAvoiding.MonoTouch into my Xamarin.iOS project.
But I've got the following error on running.
"Unknown class TPKeyboardAvoidingScrollView in InterfaceBuilder"

**Comment by fstehle** [comment]
Did you invoke `make` as stated in the readme? It should create a dll-File which you can import in your Xamarin.iOS project.

**Comment by Paul-N** [comment]
I have similar issue but with TPKeyboardAvoidingCollectionView class setted as type of CollectionView property of UICollectionViewController in my storyboard. The solution of problem was to add TPKeyboardAvoidingCollectionView class to my LinkerPleaseInclude.cs.

**Comment by Athosone** [comment]
can you link your file plz?

**Comment by Paul-N** [comment]
`using System;
using System.Collections.Specialized;
using System.Windows.Input;
using UIKit;
using TPKeyboardAvoiding;
using Foundation;

#pragma warning disable 0219
namespace YourNamespace.Touch
{
    // This class is never actually executed, but when Xamarin linking is enabled it does how to ensure types and properties
    // are preserved in the deployed app
    [Foundation.Preserve(AllMembers = true)]
    public class LinkerPleaseInclude
    {
        public void Include(UIButton uiButton)
        {
            uiButton.TouchUpInside += (s, e) =>
                                      uiButton.SetTitle(uiButton.Title(UIControlState.Normal), UIControlState.Normal);
        }

```
    public void Include(UIBarButtonItem barButton)
    {
        barButton.Clicked += (s, e) =>
                             barButton.Title = barButton.Title + "";
    }

    public void Include(UITextField textField)
    {
        textField.Text = textField.Text + "";
        textField.EditingChanged += (sender, args) => { textField.Text = ""; };
    }

    public void Include(UITextView textView)
    {
        textView.Text = textView.Text + "";
        textView.Changed += (sender, args) => { textView.Text = ""; };
    }

    public void Include(UILabel label)
    {
        label.Text = label.Text + "";
    }

    public void Include(UIImageView imageView)
    {
        imageView.Image = new UIImage(imageView.Image.CGImage);
    }

    public void Include(UIDatePicker date)
    {
        date.Date = date.Date.AddSeconds(1);
        date.ValueChanged += (sender, args) =>
        {
                date.Date = NSDate.Now;
        };
    }

    public void Include(UISlider slider)
    {
        slider.Value = slider.Value + 1;
        slider.ValueChanged += (sender, args) => { slider.Value = 1; };
    }

    public void Include(UIProgressView progress)
    {
        progress.Progress = progress.Progress + 1;
    }

    public void Include(UISwitch sw)
    {
        sw.On = !sw.On;
        sw.ValueChanged += (sender, args) => { sw.On = false; };
    }

    public void Include(INotifyCollectionChanged changed)
    {
        changed.CollectionChanged += (s,e) => { var test = string.Format("{0}{1}{2}{3}{4}", e.Action,e.NewItems, e.NewStartingIndex, e.OldItems, e.OldStartingIndex); } ;
    }

    public void Include(ICommand command)
    {
       command.CanExecuteChanged += (s, e) => { if (command.CanExecute(null)) command.Execute(null); };
    }

    public void Include(TPKeyboardAvoidingCollectionView collectionView)
    {
        collectionView.ScrollToActiveTextField();
        var var_ =collectionView.FocusNextTextField;
    }

    public void Include(Cirrious.CrossCore.IoC.MvxPropertyInjector ignored)
    {
        var ignored2 = new Cirrious.CrossCore.IoC.MvxPropertyInjector();
    }
}
```

}
#pragma warning restore 0219`

**Comment by Athosone** [comment]
Thanks I ll try to get it works this way...
